version: '3.4'

services:
  springbootrestexample:
    image: springbootrestexample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8090:8090
      - 8091:8091
      - 5005:5005
